name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "proffy-api-luizh" #Must be unique in Heroku
          heroku_email: "lpansarini@gmail.com"
          buildpack: "https://github.com/HashNuke/heroku-buildpack-elixir.git"
          appdir: "server"
          procfile: "web: ts-node --transpile-only --ignore-watch node_modules --respawn src/server.ts"